[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.build]
cmds = [
    "cd frontend && npm install && npm run build",
    "cd backend && npm install"
]

[phases.start]
cmd = "cd backend && npm start"
